/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

/**
 *
 * @author marcelosiedler
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        inicio tela = new inicio(Desktop);
        Desktop.add(tela);
        tela.show();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        Desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        itemGerenciar = new javax.swing.JMenuItem();
        itemListar = new javax.swing.JMenuItem();
        itemGerenciarCidade = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        itemListarCidade = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 760));

        jMenuBar1.setBackground(new java.awt.Color(102, 102, 102));
        jMenuBar1.setMargin(new java.awt.Insets(10, 0, 0, 0));
        jMenuBar1.setMaximumSize(new java.awt.Dimension(1024, 32768));

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/detetive.png"))); // NOI18N
        jMenu2.setText("Detetive");

        itemGerenciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/salvar16.png"))); // NOI18N
        itemGerenciar.setText("Gerenciar");
        itemGerenciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGerenciarActionPerformed(evt);
            }
        });
        jMenu2.add(itemGerenciar);

        itemListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/listar16.png"))); // NOI18N
        itemListar.setText("Listar");
        itemListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListarActionPerformed(evt);
            }
        });
        jMenu2.add(itemListar);

        jMenuBar1.add(jMenu2);

        itemGerenciarCidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cidades.jpeg"))); // NOI18N
        itemGerenciarCidade.setText("Cidades");

        jMenuItem1.setText("Gerenciar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        itemGerenciarCidade.add(jMenuItem1);

        itemListarCidade.setText("Listar");
        itemListarCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListarCidadeActionPerformed(evt);
            }
        });
        itemGerenciarCidade.add(itemListarCidade);

        jMenuBar1.add(itemGerenciarCidade);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/lugares.jpg"))); // NOI18N
        jMenu4.setText("Locais");
        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/suspeito.png"))); // NOI18N
        jMenu5.setText("Suspeitos");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Desktop)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemGerenciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGerenciarActionPerformed
        // TODO add your handling code here:
        //Instanciar a classe do frame interno que desejo exibir
        detetiveGerenciar tela = new detetiveGerenciar();
        //adicionar ao meu desktop
        Desktop.add(tela);
        //mando exibir o frame
        tela.show();
    }//GEN-LAST:event_itemGerenciarActionPerformed

    private void itemListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListarActionPerformed
        // TODO add your handling code here:
        detetiveListar tela = new detetiveListar();
        Desktop.add(tela);
        tela.show();
    }//GEN-LAST:event_itemListarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        cidadeGerenciar tela = new cidadeGerenciar();
        Desktop.add(tela);
        tela.show();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void itemListarCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListarCidadeActionPerformed
        // TODO add your handling code here:
         cidadeListar tela = new cidadeListar();
        //adicionar ao meu desktop
        Desktop.add(tela);
        //mando exibir o frame
        tela.show();
    }//GEN-LAST:event_itemListarCidadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuItem itemGerenciar;
    private javax.swing.JMenu itemGerenciarCidade;
    private javax.swing.JMenuItem itemListar;
    private javax.swing.JMenuItem itemListarCidade;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
