/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Janela;

import Tabela.CidadesTAB;
import Tabela.DetetiveTAB;
import Tabela.LocaisVisitadosTAB;
import Tabela.SuspeitosTAB;

/**
 *
 * @author Aluno
 */
public class PrincipalGUI extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalGUI
     */
    public PrincipalGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuDetetive = new javax.swing.JMenu();
        itemDetetiveG = new javax.swing.JMenuItem();
        itemDetetiveL = new javax.swing.JMenuItem();
        menuSuspeitos = new javax.swing.JMenu();
        itemSuspeitosG = new javax.swing.JMenuItem();
        itemSuspeitosL = new javax.swing.JMenuItem();
        menuLocaisvisitados = new javax.swing.JMenu();
        itemLocaisG = new javax.swing.JMenuItem();
        itemLocaisL = new javax.swing.JMenuItem();
        menuCidades = new javax.swing.JMenu();
        itemCidadesG = new javax.swing.JMenuItem();
        itemCidadesL = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel1.setText("TchêLoque");
        jLabel1.setMaximumSize(new java.awt.Dimension(110, 40));
        jLabel1.setPreferredSize(new java.awt.Dimension(110, 40));
        jLabel1.setVerifyInputWhenFocusTarget(false);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/detetiveIMG.gif"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel3.setText("Ramos");

        jMenuBar1.setMargin(new java.awt.Insets(15, 0, 0, 0));

        menuDetetive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/detetive.png"))); // NOI18N
        menuDetetive.setText("Detetive");

        itemDetetiveG.setText("Gerenciar");
        itemDetetiveG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDetetiveGActionPerformed(evt);
            }
        });
        menuDetetive.add(itemDetetiveG);

        itemDetetiveL.setText("Listar");
        itemDetetiveL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDetetiveLActionPerformed(evt);
            }
        });
        menuDetetive.add(itemDetetiveL);

        jMenuBar1.add(menuDetetive);

        menuSuspeitos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/suspeito.png"))); // NOI18N
        menuSuspeitos.setText("Suspeitos");

        itemSuspeitosG.setText("Gerenciar");
        itemSuspeitosG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSuspeitosGActionPerformed(evt);
            }
        });
        menuSuspeitos.add(itemSuspeitosG);

        itemSuspeitosL.setText("Listar");
        itemSuspeitosL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSuspeitosLActionPerformed(evt);
            }
        });
        menuSuspeitos.add(itemSuspeitosL);

        jMenuBar1.add(menuSuspeitos);

        menuLocaisvisitados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/lugares.gif"))); // NOI18N
        menuLocaisvisitados.setText("Locais Visitados");

        itemLocaisG.setText("Gerenciar");
        itemLocaisG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLocaisGActionPerformed(evt);
            }
        });
        menuLocaisvisitados.add(itemLocaisG);

        itemLocaisL.setText("Listar");
        itemLocaisL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLocaisLActionPerformed(evt);
            }
        });
        menuLocaisvisitados.add(itemLocaisL);

        jMenuBar1.add(menuLocaisvisitados);

        menuCidades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/cidades.jpeg"))); // NOI18N
        menuCidades.setText("Cidades");

        itemCidadesG.setText("Gerenciar");
        itemCidadesG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCidadesGActionPerformed(evt);
            }
        });
        menuCidades.add(itemCidadesG);

        itemCidadesL.setText("Listar");
        itemCidadesL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCidadesLActionPerformed(evt);
            }
        });
        menuCidades.add(itemCidadesL);

        jMenuBar1.add(menuCidades);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemDetetiveGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDetetiveGActionPerformed
        DetetiveGUI d = new DetetiveGUI();
        d.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        d.setVisible(true);  
    }//GEN-LAST:event_itemDetetiveGActionPerformed

    private void itemDetetiveLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDetetiveLActionPerformed
        DetetiveTAB d = new DetetiveTAB();
        d.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        d.setVisible(true);
    }//GEN-LAST:event_itemDetetiveLActionPerformed

    private void itemSuspeitosGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSuspeitosGActionPerformed
        SuspeitosGUI s = new SuspeitosGUI();
        s.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        s.setVisible(true);  
    }//GEN-LAST:event_itemSuspeitosGActionPerformed

    private void itemSuspeitosLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSuspeitosLActionPerformed
        SuspeitosTAB s = new SuspeitosTAB();
        s.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        s.setVisible(true);  
    }//GEN-LAST:event_itemSuspeitosLActionPerformed

    private void itemLocaisGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLocaisGActionPerformed
        LocaisVisitadosGUI lv = new LocaisVisitadosGUI();
        lv.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        lv.setVisible(true);  
    }//GEN-LAST:event_itemLocaisGActionPerformed

    private void itemLocaisLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLocaisLActionPerformed
        LocaisVisitadosTAB lv = new LocaisVisitadosTAB();
        lv.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        lv.setVisible(true); 
    }//GEN-LAST:event_itemLocaisLActionPerformed

    private void itemCidadesGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCidadesGActionPerformed
        CidadesGUI c = new CidadesGUI();
        c.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        c.setVisible(true); 
    }//GEN-LAST:event_itemCidadesGActionPerformed

    private void itemCidadesLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCidadesLActionPerformed
        CidadesTAB c = new CidadesTAB();
        c.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        c.setVisible(true); 
    }//GEN-LAST:event_itemCidadesLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemCidadesG;
    private javax.swing.JMenuItem itemCidadesL;
    private javax.swing.JMenuItem itemDetetiveG;
    private javax.swing.JMenuItem itemDetetiveL;
    private javax.swing.JMenuItem itemLocaisG;
    private javax.swing.JMenuItem itemLocaisL;
    private javax.swing.JMenuItem itemSuspeitosG;
    private javax.swing.JMenuItem itemSuspeitosL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuCidades;
    private javax.swing.JMenu menuDetetive;
    private javax.swing.JMenu menuLocaisvisitados;
    private javax.swing.JMenu menuSuspeitos;
    // End of variables declaration//GEN-END:variables
}
