
DROP TABLE ALUNO;

CREATE TABLE ALUNO (
MATRICULA	BIGINT NOT NULL PRIMARY KEY,
NOME		VARCHAR (100) NOT NULL,
PLACACARRO	CHAR (7) NOT NULL,
SEXO		CHAR (1) NOT NULL,
UF		CHAR (2) NOT NULL,
NOTAFINAL	NUMERIC (4,2) NOT NULL
);

INSERT INTO ALUNO (MATRICULA,NOME,PLACACARRO,SEXO,UF,NOTAFINAL)
VALUES (20122623561,'MARCOS PEREIRA','IGU4506','M','RS',10.00);

INSERT INTO ALUNO (MATRICULA,NOME,PLACACARRO,SEXO,UF,NOTAFINAL)
VALUES (20132620261,'VITINHO HORUGO','IGU0006','M','RS',08.00);

SELECT * FROM ALUNO 


